### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by shethpriyank** [zerodha/mii-lama#10]
listmonk@listmonk:~$ cd /etc/pro
profile.d/  prometheus/
listmonk@listmonk:~$ cd /etc/prometheus/
listmonk@listmonk:/etc/prometheus$ sudo docker-compose up -d
Creating network "prometheus_monitor-net" with driver "bridge"
Creating prometheus ... error

ERROR: for prometheus  Cannot start service prometheus: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/prometheus/prometheus.sample.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /etc/prometheus/prometheus.sample.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for prometheus  Cannot start service prometheus: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/prometheus/prometheus.sample.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /etc/prometheus/prometheus.sample.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
listmonk@listmonk:/etc/prometheus$ docker container ls -a
CONTAINER ID   IMAGE                     COMMAND                  CREATED         STATUS    PORTS      NAMES
595f220d81d1   prom/prometheus:v2.43.0   "/bin/prometheus --c…"   4 minutes ago   Created   9090/tcp   prometheus
listmonk@listmonk:/etc/prometheus$ dir
config.toml  docker-compose.yml  prometheus.sample.yml
listmonk@listmonk:/etc/prometheus$

**Comment by mr-karan** [comment]
Not sure what `listmonk` container in these logs mean. Please follow the install instructions mentioned here: https://github.com/zerodha/mii-lama#installation

**Comment by mr-karan** [comment]
Closing in favor of https://github.com/zerodha/mii-lama/issues/9
