### ISSUE TITLE
mii-lama      | panic: (29, 11): unexpected token Integer

### ISSUE THREAD

**Issue by sifydinesh** [zerodha/mii-lama#11]
Hi i am getting below error

mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama      | panic: (29, 11): unexpected token Integer
mii-lama      | 
mii-lama      | goroutine 1 [running]:
mii-lama      | main.main()
mii-lama      | 	/home/runner/work/mii-lama/mii-lama/cmd/main.go:22 +0x6e5
mii-lama exited with code 2
mii-lama exited with code 2
mii-lama exited with code 2
mii-lama exited with code 2
mii-lama exited with code 2
m

**Comment by mr-karan** [comment]
Can you post the config.toml to debug?

**Comment by sifydinesh** [comment]
hi @mr-karan 
below is the config.toml, i have removed login id and passwords

[app]
log_level = "debug" # To enable debug logging, level should be `debug`.
sync_interval = "5m" # Interval at which the app should fetch data from metrics store.
retry_interval = "5s" # Interval at which the app should retry if the previous request failed.
max_retries = 3 # Maximum number of retries for a failed request.

[lama.nse]
url = "https://lama.nseindia.com/api/V1" # Endpoint for NSE LAMA API Gateway
login_id = ""
member_id = ""
password = ""
timeout = "30s" # Timeout for HTTP requests
idle_timeout = "5m" # Idle timeout for HTTP requests
exchange_id = 1 # 1=National Stock Exchange

[prometheus]
endpoint = "http://prometheus:9090" # Endpoint for Prometheus API
query_path = "/api/v1/query" # Endpoint for Prometheus query API
username = "" # HTTP Basic Auth username
password = "" # HTTP Basic Auth password
timeout = "10s" # Timeout for HTTP requests
idle_timeout = "5m" # Idle timeout for HTTP requests
max_idle_conns = 10
config_path = "/etc/prometheus/prometheus.yml" # Path to Prometheus config file. This is used to load a list of hosts to fetch metrics for.

[metrics.hardware] # Define Prometheus queries for hardware metrics
hosts = [] # List of hosts to fetch metrics for. Keep this empty to fetch metrics for all hosts defined in `prometheus.config_path` file.
cpu = '100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100)
memory = '100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100)
disk = '100.0 - 100 * (((windows_logical_disk_free_bytes{volume=~".:"} / 1024 / 1024 ) / (windows_logical_disk_size_bytes{volume=~".:"} / 1024 / 1024)))
uptime = '(node_time_seconds{hostname="10.10.0.228"} - node_boot_time_seconds{hostname="10.10.0.228"}) / 60'

[metrics.database] # Define Prometheus queries for db metrics
hosts = [] # List of hosts to fetch metrics for. Keep this empty to fetch metrics for all hosts defined in `prometheus.config_path` file.
status = 'up{hostname="10.10.0.228"}'

[metrics.network]
packet_errors = 'sum(rate(node_network_receive_errs_total{hostname="%s"}[5m])) + sum(rate(node_network_transmit_errs_total{hostname="%s"}[5m]))'
hosts = []

**Comment by mr-karan** [comment]
Your `metrics.hardware` section has issues:

```
cpu = '100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100)'
memory = '100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100)'
disk = '100.0 - 100 * (((windows_logical_disk_free_bytes{volume=".:"} / 1024 / 1024 ) / (windows_logical_disk_size_bytes{volume=".:"} / 1024 / 1024)))'
```

They were missing a closing `'`, which I've added above ^.

**Comment by sifydinesh** [comment]
@mr-karan I have done the changes as suggested, do I need to docker-compose again to apply the changes? because I am getting the same error after change

**Comment by mr-karan** [comment]
Yes you will need to restart the container so the app starts with new config.

**Comment by sifydinesh** [comment]
@mr-karan Thanks, I have restarted the container, now getting below alerts, do I need to change some network setting?

time=2023-08-01T05:27:23.196Z level=ERROR source=/home/runner/work/mii-lama/mii-lama/cmd/main.go:51 msg="failed to init nse manager" component=mii-lama error="failed to login to NSE API: failed to send HTTP request: Post \"https://lama.nseindia.com/api/V1/api/V1/auth/login\": dial tcp: lookup lama.nseindia.com on 127.0.0.11:53: server misbehaving"

**Comment by sifydinesh** [comment]
this is the problem "[https://lama.nseindia.com/api/V1/api/V1/auth/login\ let me correct

**Comment by mr-karan** [comment]
The URL should not have `/api/V1`. Only the root endpoint like `url = "https://lama.uat.nseindia.com"` should be there.
