### ISSUE TITLE
Internal Login Error

### ISSUE THREAD

**Issue by sifydinesh** [zerodha/mii-lama#13]
Hi i am getting below error, i have passed login details correctly.

time=2023-09-04T05:12:31.071Z level=ERROR source=/home/runner/work/mii-lama/mii-lama/cmd/main.go:51 msg="failed to init nse manager" component=mii-lama error="failed to login to NSE API: failed to send HTTP request: Post \"https://lama.nseindia.com/api/V1/auth/login\": stream error: stream ID 1; INTERNAL_ERROR; received from peer"

**Comment by mr-karan** [comment]
Hi.

This error is specific to the host and networking environment between the client and remote address, not related to the program.

**Comment by sifydinesh** [comment]
hi Karan, 

Postman is working on same host where mii-lama is configured and also there is no issue from network end, i have verified the same, if postman is working on the same host then our mii-lama should work. 

i have observed in nse.go code we have given http network and http client and http header and the error 

![noname1](https://github.com/zerodha/mii-lama/assets/127955072/f29251d5-924c-4d58-b2e9-4510b9f622b6)
![noname](https://github.com/zerodha/mii-lama/assets/127955072/73bbce7e-bfd8-40e7-b6f5-3dde5a467b36)

**Comment by sifydinesh** [comment]
ERROR source=/home/runner/work/mii-lama/mii-lama/internal/nse/nse.go:185 msg="HTTP request failed"
