### ISSUE TITLE
stream error: stream ID 1; INTERNAL_ERROR; received from peer"

### ISSUE THREAD

**Issue by sifydinesh** [zerodha/mii-lama#14]
Hi i have done the changes in config.toml for NSE url but its still taking the old one and throwing error.| time=2023-10-04T09:20:50.639Z level=ERROR source=/home/runner/work/mii-lama/mii-lama/cmd/main.go:51 msg="failed to init nse manager" component=mii-lama error="failed to login to NSE API: failed to send HTTP request: Post \"https://lama.nseindia.com/api/V1/auth/login\": stream error: stream ID 1; INTERNAL_ERROR; received from peer"
mii-lama exited with code 1

below url is passed in config.toml
[lama.nse]
url = "https://lama.nseindia.com" # Endpoint for NSE LAMA API Gateway

**Comment by mr-karan** [comment]
Dupe: https://github.com/zerodha/mii-lama/issues/13#issuecomment-1704640811
