### ISSUE TITLE
failed to create HTTP request: parse \": http://lama.uat.nseindia.com/api/V1/auth/login\": missing protocol scheme"

### ISSUE THREAD

**Issue by sifydinesh** [zerodha/mii-lama#15]
Hi Karan, 
Sorry to bother you again and again, can you please help me with below error, i have given correct url as per your last suggestion. 

i am getting below error- 
time=2023-10-11T06:30:59.373Z level=ERROR source=/home/runner/work/mii-lama/mii-lama/cmd/main.go:51 msg="failed to init nse manager" component=mii-lama error="failed to login to NSE API: failed to create HTTP request: parse \": http://lama.uat.nseindia.com/api/V1/auth/login\": missing protocol scheme"

below is config toml
[lama.nse]
url = ": http://lama.uat.nseindia.com" # Endpoint for NSE LAMA API Gateway

**Comment by mr-karan** [comment]
`url = ": http://lama.uat.nseindia.com/" # Endpoint for NSE LAMA API Gateway`

The URL is wrong. 

```
url = "http://lama.uat.nseindia.com/"
```
