### ISSUE TITLE
stream error: stream ID 1; INTERNAL_ERROR; received from peer

### ISSUE THREAD

**Issue by sifydinesh** [zerodha/mii-lama#17]
Hi i am getting below error in mii-lama where i am able to login with the same credentials via postman from same system where mii-lama configured, kindly check and help.

mii-lama application Error : 
time=2023-12-21T08:28:48.942Z level=ERROR source=/home/runner/work/mii-lama/mii-lama/cmd/main.go:51 msg="failed to init nse manager" component=mii-lama error="failed to login to NSE API: failed to send HTTP request: Post \"https://lama.nseindia.com/api/V1/auth/login\": stream error: stream ID 1; INTERNAL_ERROR; received from peer"

Postman login success
<img width="856" alt="image" src="https://github.com/zerodha/mii-lama/assets/127955072/0dd4c4cc-01ee-4b69-b780-f31267326a06">

**Comment by mr-karan** [comment]
![Uploading image.png…]()

**Comment by sifydinesh** [comment]
hi Karan,

Postman is working on same host where mii-lama is configured and also there is no issue from network end, i have verified the same, if postman is working on the same host then our mii-lama should work.

i have observed in nse.go code we have given http network and http client and http header and the error is ERROR source=/home/runner/work/mii-lama/mii-lama/internal/nse/nse.go:185 msg="HTTP request failed"

![noname1](https://github.com/zerodha/mii-lama/assets/127955072/3a82f39c-34e0-4509-bd4b-00086b45e880)
![noname](https://github.com/zerodha/mii-lama/assets/127955072/c4423a07-c0c0-4005-8de1-77820e039763)
